"""The dataset card.

A card that is written by hand is a card that is wrong, so the test that
matters is that every figure in it comes from the table: change the data,
change the card. The rest is rendering, and the rendering is only worth
checking where getting it wrong would be silent — a nullable tier, a missing
checksum, a coverage percentage of the wrong column.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from src.ingestion.base import BENCHMARK_COLUMNS, POST_MATCH_COLUMNS, PRE_MATCH_COLUMNS
from src.storage.duckdb_store import DuckDBStore
from src.validation.card import build_card, competition_coverage, totals, write_card
from src.validation.matches import match_checks
from src.validation.report import run_checks
from tests.factories import league_frame, league_registry


@pytest.fixture
def store(tmp_path: Path) -> DuckDBStore:
    path = tmp_path / "matches.parquet"
    league_frame().to_parquet(path, index=False)
    with DuckDBStore.open_matches(path) as opened:
        yield opened


@pytest.fixture
def card(store: DuckDBStore) -> str:
    report = run_checks(store.read_matches(), match_checks(league_registry()))
    return build_card(store, report)


def test_the_headline_figures_come_from_the_table(card: str) -> None:
    assert "| Matches | 5,320 |" in card
    assert "| Competitions | 1 |" in card
    assert "| Seasons | 14 |" in card
    assert "| Teams | 20 |" in card


def test_the_class_balance_is_reported(card: str) -> None:
    """45 / 27 / 28 is what the factory generates, and what the real ingest
    measures. A card that reported something else would mean the aggregate is
    reading the wrong column."""
    assert "| Home / draw / away | 45% / 27% / 28% |" in card


def test_the_coverage_table_has_one_row_per_competition(store: DuckDBStore) -> None:
    coverage = competition_coverage(store)
    assert len(coverage) == 1
    assert coverage.iloc[0]["competition_id"] == "ENG_1"
    assert int(coverage.iloc[0]["teams"]) == 20
    assert coverage.iloc[0]["stats"] == pytest.approx(1.0)


def test_teams_are_counted_from_both_sides_of_the_fixture(store: DuckDBStore) -> None:
    """Counting distinct home teams misses any club that only ever played
    away — rare in a league, routine in a cup."""
    assert int(competition_coverage(store).iloc[0]["teams"]) == 20


def test_the_validation_report_is_embedded(card: str) -> None:
    """The card and the pipeline's gate must never disagree about what was
    checked, which is why the report is passed in rather than re-run here."""
    assert "5,320 matches" in card
    assert "match ids are unique" in card


def test_the_leakage_classification_is_spelled_out(card: str) -> None:
    assert f"Pre-match ({len(PRE_MATCH_COLUMNS)} columns)" in card
    assert f"Post-match ({len(POST_MATCH_COLUMNS)} columns)" in card
    for column in BENCHMARK_COLUMNS:
        assert f"`{column}`" in card
    assert "`home_shots`" in card


def test_the_checksum_appears_only_when_the_file_is_named(
    store: DuckDBStore, tmp_path: Path
) -> None:
    """The card's numbers are attached to specific bytes, or to nothing."""
    report = run_checks(store.read_matches(), match_checks(league_registry()))
    assert "SHA-256" not in build_card(store, report)

    path = tmp_path / "matches.parquet"
    league_frame(seasons=["2024-25"]).to_parquet(path, index=False)
    assert "SHA-256" in build_card(store, report, source=path)


def test_a_named_but_absent_file_is_skipped_rather_than_raising(
    store: DuckDBStore, tmp_path: Path
) -> None:
    report = run_checks(store.read_matches(), match_checks(league_registry()))
    assert "SHA-256" not in build_card(store, report, source=tmp_path / "gone.parquet")


def test_a_competition_without_a_tier_renders_as_a_dash(tmp_path: Path) -> None:
    """Cups have no tier, and DuckDB returns the null as pandas' NAType — which
    is neither None nor a float, so the obvious `is None` test passes it
    straight through to int() and raises."""
    path = tmp_path / "cup.parquet"
    league_frame(competition_id="ENG_CUP", name="FA Cup", tier=None).to_parquet(path, index=False)
    with DuckDBStore.open_matches(path) as store:
        report = run_checks(
            store.read_matches(),
            match_checks(league_registry(competition_id="ENG_CUP", name="FA Cup", tier=None)),
        )
        card = build_card(store, report)
    assert "| FA Cup (`ENG_CUP`) | England | - |" in card


def test_totals_are_a_single_row(store: DuckDBStore) -> None:
    assert len(totals(store)) == 1


def test_the_card_says_it_is_generated(card: str) -> None:
    """A hand-edited figure is a figure that no longer describes the data, and
    the only defence is telling the reader the file is overwritten."""
    assert "GENERATED by scripts/validate_data.py" in card


def test_writing_the_card_creates_its_directory(tmp_path: Path) -> None:
    destination = write_card(tmp_path / "docs" / "DATASET_CARD.md", "# card\n")
    assert destination.read_text(encoding="utf-8") == "# card\n"
