"""The model card, rendered from four small frames and nothing else.

The point of the split between this and `src/pipelines/report.py` is that the
rendering can be tested without a fitted model, a Parquet file or a backtest —
so what is checked here is what the card *says*: that the numbers it was handed
appear, that the sections a reader needs are present whether or not the
optional ones are, and that the limitations are not quietly droppable.
"""

from __future__ import annotations

import pandas as pd

from src.evaluation.model_card import CARD_FILENAME, ModelCard, _table

SCORES = pd.DataFrame(
    {
        "forecaster": ["bookmaker", "ensemble-calibrated", "dixon_coles", "class_prior", "mlp"],
        "n": [59001, 59001, 59001, 59001, 59001],
        "log_loss": [0.9993, 1.0156, 1.0277, 1.0751, 1.0203],
        "rps": [0.2031, 0.2082, 0.2114, 0.2284, 0.2091],
        "accuracy": [0.5055, 0.4931, 0.4850, 0.4370, 0.4913],
    }
)

RELIABILITY = pd.DataFrame(
    {
        "bin": [2, 5],
        "lower": [0.2, 0.5],
        "upper": [0.3, 0.6],
        "n": [77867, 14012],
        "predicted": [0.2603, 0.5437],
        "observed": [0.2635, 0.5438],
        "gap": [0.0032, 0.0001],
    }
)

WORST = pd.DataFrame(
    {
        "competition_id": ["CHN_1", "ARG_CUP"],
        "matches": [900, 569],
        "calibration_error": [0.0181, 0.0154],
    }
)


def _card(**overrides: object) -> ModelCard:
    fields: dict[str, object] = {
        "name": "ensemble-calibrated",
        "version": "0.10.0",
        "settings": {"members": "xgboost, logistic_regression, mlp", "columns": 30},
        "scores": SCORES,
        "reliability": RELIABILITY,
        "matches": 59001,
        "competitions": 39,
        "folds": 5,
        "trained_from": "1993-07-23",
        "trained_to": "2026-09-01",
        "columns": tuple(f"column_{index}" for index in range(30)),
    }
    return ModelCard(**{**fields, **overrides})  # type: ignore[arg-type]


def test_the_card_is_named_for_the_model_it_describes() -> None:
    assert _card().render().startswith("# Model card — ensemble-calibrated")


def test_it_says_it_was_generated_and_by_what() -> None:
    """A hand-edited figure is a figure that no longer describes the model, and
    the next run overwrites it anyway."""
    rendered = _card().render()
    assert "GENERATED by scripts/model_card.py" in rendered
    assert "0.10.0" in rendered


def test_nothing_in_it_changes_between_two_renderings() -> None:
    """No timestamp. The subject is a version-controlled model, and a header
    that moves on every run turns "the numbers changed" into a diff nobody
    reads."""
    assert _card().render() == _card().render()


def test_what_it_was_trained_on_is_stated_in_figures() -> None:
    rendered = _card().render()
    assert "| Matches scored | 59,001 |" in rendered
    assert "| Competitions | 39 |" in rendered
    assert "| History | 1993-07-23 to 2026-09-01 |" in rendered
    assert "| Input columns | 30 |" in rendered


def test_the_score_table_carries_the_model_and_what_it_is_read_against() -> None:
    """A model's log loss alone is a number with no scale. The bookmaker is the
    ceiling, the prior is the floor, and the rating is what it replaced."""
    rendered = _card().render()
    for row in ("ensemble-calibrated", "bookmaker", "dixon_coles", "class_prior"):
        assert f"| {row} |" in rendered


def test_a_forecaster_the_card_is_not_about_is_left_out() -> None:
    """Five rows of other families is a leaderboard, and this is a card."""
    assert "| mlp |" not in _card().render()


def test_the_pooled_calibration_error_is_stated() -> None:
    """Weighted by bin: 0.0032 over 77,867 statements and 0.0001 over 14,012."""
    assert "**0.0027**" in _card().render()


def test_the_per_class_section_appears_only_when_there_is_one() -> None:
    assert "### By class" not in _card().render()
    with_classes = _card(per_class={"H": RELIABILITY, "D": RELIABILITY, "A": RELIABILITY})
    rendered = with_classes.render()
    assert "### By class" in rendered
    assert rendered.count("| 91,879 |") == 3


def test_an_empty_class_table_is_skipped_rather_than_rendered_as_zero() -> None:
    """A class the model never states a probability for has no calibration
    error; a row saying 0.0000 would read as a perfect one."""
    rendered = _card(per_class={"H": RELIABILITY, "D": pd.DataFrame()}).render()
    assert rendered.count("calibration error |") == 1
    assert "| D |" not in rendered


def test_the_worst_competitions_appear_only_when_measured() -> None:
    assert "### Where it is least reliable" not in _card().render()
    rendered = _card(worst=WORST).render()
    assert "### Where it is least reliable" in rendered
    assert "| CHN_1 | 900 | 0.0181 |" in rendered


def test_the_limitations_are_a_section_and_not_a_disclaimer() -> None:
    """The part that changes what someone does with the model. Each of these is
    a measured fact from this project rather than boilerplate."""
    rendered = _card().render()
    assert "## What it must not be used for" in rendered
    for limitation in ("Betting", "no history", "needs the reason", "in-play"):
        assert limitation in rendered


def test_how_it_was_built_lists_the_settings_it_was_given() -> None:
    rendered = _card().render()
    assert "| `members` | xgboost, logistic_regression, mlp |" in rendered
    assert "| `columns` | 30 |" in rendered


def test_a_card_with_nothing_measured_still_renders() -> None:
    """A card is a document. One built before the backtest ran should say so
    rather than fail — the alternative is a command that cannot tell a missing
    run from a broken one."""
    rendered = _card(scores=pd.DataFrame(), reliability=pd.DataFrame()).render()
    assert "_(nothing to report)_" in rendered
    assert "nan" in rendered


def test_a_frame_renders_as_markdown_rows() -> None:
    rows = _table(pd.DataFrame({"a": [1000], "b": [0.5]}))
    assert rows[0] == "| a | b |"
    assert rows[-1] == "| 1,000 | 0.5000 |"


def test_the_card_has_a_fixed_filename() -> None:
    assert CARD_FILENAME == "MODEL_CARD.md"
